apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: akh8e4xvj-go
  janus-idp.io/tekton: akh8e4xvj-go
  backstage.io/kubernetes-id: akh8e4xvj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: akh8e4xvj-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
