apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: akh8e4xvj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: akh8e4xvj-go 
  name: akh8e4xvj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: akh8e4xvj-go 
